apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-tls
  labels:
    app: {{ .Chart.Name }}
spec:
  secretName: {{ .Chart.Name }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.dns.prefix }}{{ .Values.dns.appName }}.{{ .Values.dns.domain }}
