get:
  summary: Get organization settings list.
  operationId: getOrganizationSettingsList
  tags:
    - organizations
    - settings
  parameters:
    - name: id
      in: path
      description: Organization ID.
      required: true
      schema:
        type: integer
        format: int32
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/organizations/OrganizationSettingDto.yaml'
    '401':
      $ref: 'eventuras-api.v3.yaml#/components/responses/UnauthorizedError'
    '404':
      $ref: 'eventuras-api.v3.yaml#/components/responses/NotFound'
    '403':
      $ref: 'eventuras-api.v3.yaml#/components/responses/ForbiddenError'
    '500':
      $ref: 'eventuras-api.v3.yaml#/components/responses/InternalServerError'

put:
  summary: Update organization settings.
  operationId: updateOrganizationSettings
  tags:
    - organizations
    - settings
  parameters:
    - name: id
      in: path
      description: Organization ID.
      required: true
      schema:
        type: integer
        format: int32
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/organizations/OrganizationSettingValueDto.yaml'
  responses:
    '200':
      description: OK
    '400':
      $ref: 'eventuras-api.v3.yaml#/components/responses/InvalidRequestError'
    '401':
      $ref: 'eventuras-api.v3.yaml#/components/responses/UnauthorizedError'
    '404':
      $ref: 'eventuras-api.v3.yaml#/components/responses/NotFound'
    '403':
      $ref: 'eventuras-api.v3.yaml#/components/responses/ForbiddenError'
    '500':
      $ref: 'eventuras-api.v3.yaml#/components/responses/InternalServerError'
