apiVersion: v2
name: eventuras-api
description: Eventuras Backend API - RESTful API for course, event, and conference management
type: application
version: 0.1.0
appVersion: "0.0.0" # Actual version set by CI
