version: "3"

services:
  web:
    image: losolio/eventuras-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=eventuras;Username=eventuras;Password=Str0ng!Pasword"
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: eventuras_db
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eventuras
      POSTGRES_PASSWORD: "Str0ng!Pasword"
      POSTGRES_DB: eventuras
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=eventuras --username=eventuras"]
      interval: 5s
      timeout: 5s
      retries: 10
