name: Api project CI

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - "apps/api/**"
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        default: "10.x"
        type: string

env:
  ORGANIZATION_NAME: losolio
  IMAGE_NAME: eventuras

jobs:
  format:
    name: dotnet format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api/
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/util-dotnet-install
      - name: dotnet format
        run: dotnet format --verify-no-changes

  build:
    name: Build project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api/
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/util-dotnet-install
      - name: Restore dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore -o ./Release

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./apps/api/
    strategy:
      matrix:
        test_set:
          - name: "Unit Tests"
            path: "./tests/Eventuras.UnitTests/Eventuras.UnitTests.csproj"
          - name: "Web API Integration Tests"
            path: "./tests/Eventuras.WebApi.Tests/Eventuras.WebApi.Tests.csproj"
          - name: "Services Integration Tests"
            path: "./tests/Eventuras.Services.Tests/Eventuras.Services.Tests.csproj"
          - name: "Converto Service Tests"
            path: "./tests/Eventuras.Services.Converto.Tests/Eventuras.Services.Converto.Tests.csproj"
          - name: "Email Communication Tests"
            path: "./tests/Losol.Communication.Email.Tests/Losol.Communication.Email.Tests.csproj"
    name: ${{ matrix.test_set.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/util-dotnet-install
      - name: Run tests
        run: dotnet test --project ${{ matrix.test_set.path }}

  docker:
    name: Docker build
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api/
    outputs:
      docker_tag: ${{ env.DOCKER_TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

      - name: Set Docker Tag
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}:$(date +'%Y%m%d-%H%M%S')-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api/
          push: true
          tags: ${{ env.DOCKER_TAG }}

      - name: Output Docker tag
        if: github.ref == 'refs/heads/main'
        run: echo "Docker tag is ${{ env.DOCKER_TAG }}"

  deploy-docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docker
    environment: api-staging

    steps:
      - name: Deploy to Azure
        id: deploy-to-azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ needs.docker.outputs.docker_tag }}
